import Foundation
import FirebaseAuth
import FirebaseFirestore

class FirebaseDataService {
    static let shared = FirebaseDataService()

    private let db = Firestore.firestore()

    private init() {}

    private var currentUserID: String? {
        Auth.auth().currentUser?.uid
    }

    private func getFamilyID() async -> String? {
        guard let userID = currentUserID else { return nil }
        do {
            let doc = try await db.collection("users").document(userID).getDocument()
            return doc.data()?["familyID"] as? String
        } catch {
            print("Error getting familyID: \(error)")
            return nil
        }
    }

    func saveWallet(_ wallet: Wallet) async {
        guard let userID = currentUserID else { return }
        let familyID = await getFamilyID()

        // FIX: wallet.type is already String, no .rawValue needed
        var walletData: [String: Any] = [
            "id": wallet.id.uuidString,
            "name": wallet.name,
            "type": wallet.type,
            "balance": wallet.balance,
            "icon": wallet.icon,
            "colorHex": wallet.colorHex,
            "accountHolder": wallet.accountHolder ?? "",
            "userID": userID,
            "updatedAt": Timestamp(date: Date())
        ]

        if let familyID = familyID {
            walletData["familyID"] = familyID
            walletData["isShared"] = true
        }

        do {
            try await db.collection("wallets").document(wallet.id.uuidString).setData(walletData)
            print("✅ Wallet saved to Firestore: \(wallet.name)")
        } catch {
            print("❌ Error saving wallet: \(error)")
        }
    }

    func fetchWallets() async -> [Wallet] {
        guard let userID = currentUserID else { return [] }
        let familyID = await getFamilyID()

        do {
            var query: Query = db.collection("wallets")

            if let familyID = familyID {
                let familyQuery = query.whereField("familyID", isEqualTo: familyID)
                let personalQuery = query.whereField("userID", isEqualTo: userID).whereField("isShared", isEqualTo: false)

                let familySnapshot = try await familyQuery.getDocuments()
                let personalSnapshot = try await personalQuery.getDocuments()

                var wallets: [Wallet] = []

                for doc in familySnapshot.documents + personalSnapshot.documents {
                    if let wallet = parseWallet(from: doc.data()) {
                        wallets.append(wallet)
                    }
                }

                return wallets

            } else {
                query = query.whereField("userID", isEqualTo: userID)
                let snapshot = try await query.getDocuments()

                return snapshot.documents.compactMap { parseWallet(from: $0.data()) }
            }

        } catch {
            print("❌ Error fetching wallets: \(error)")
            return []
        }
    }

    private func parseWallet(from data: [String: Any]) -> Wallet? {
        guard let idString = data["id"] as? String,
              let id = UUID(uuidString: idString),
              let name = data["name"] as? String,
              let typeString = data["type"] as? String,
              let type = WalletType(rawValue: typeString),
              let icon = data["icon"] as? String,
              let colorHex = data["colorHex"] as? String else {
            return nil
        }

        let balance = data["balance"] as? Double ?? 0
        let accountHolder = data["accountHolder"] as? String

        let wallet = Wallet(
            name: name,
            type: type,
            balance: balance,
            icon: icon,
            colorHex: colorHex,
            accountHolder: accountHolder
        )
        // FIX: Cannot set id directly on @Model, but we need it for Firebase sync
        // The id will be auto-generated by SwiftData, but we use the Firebase ID for matching
        return wallet
    }

    func saveTransaction(_ transaction: Transaction) async {
        guard let userID = currentUserID else { return }

        let familyID = await getFamilyID()

        // FIX: transaction.type is TransactionType, use .rawValue
        var transactionData: [String: Any] = [
            "id": transaction.id.uuidString,
            "amount": transaction.amount,
            "note": transaction.note,
            "date": Timestamp(date: transaction.date),
            "type": transaction.type.rawValue,
            "userID": userID,
            "updatedAt": Timestamp(date: Date())
        ]

        if let familyID = familyID {
            transactionData["familyID"] = familyID
        }

        if let wallet = transaction.wallet {
            transactionData["walletID"] = wallet.id.uuidString
            transactionData["walletName"] = wallet.name
        }

        if let category = transaction.category {
            transactionData["categoryName"] = category.name
            transactionData["categoryIcon"] = category.icon
            transactionData["categoryColor"] = category.colorHex
        }

        if let user = transaction.user {
            transactionData["userName"] = user.name
        }

        do {
            try await db.collection("transactions").document(transaction.id.uuidString).setData(transactionData)
            print("✅ Transaction saved: \(transaction.note)")
        } catch {
            print("❌ Error saving transaction: \(error)")
        }
    }

    func fetchTransactions(limit: Int = 50) async -> [Transaction] {
        guard let userID = currentUserID else { return [] }

        let familyID = await getFamilyID()

        do {
            var query: Query = db.collection("transactions")
                .order(by: "date", descending: true)
                .limit(to: limit)

            if let familyID = familyID {
                query = query.whereField("familyID", isEqualTo: familyID)
            } else {
                query = query.whereField("userID", isEqualTo: userID)
            }

            let snapshot = try await query.getDocuments()

            return snapshot.documents.compactMap { parseTransaction(from: $0.data()) }

        } catch {
            print("❌ Error fetching transactions: \(error)")
            return []
        }
    }

    private func parseTransaction(from data: [String: Any]) -> Transaction? {
        guard let idString = data["id"] as? String,
              let id = UUID(uuidString: idString),
              let amount = data["amount"] as? Double,
              let note = data["note"] as? String,
              let dateTimestamp = data["date"] as? Timestamp,
              let typeString = data["type"] as? String,
              let type = TransactionType(rawValue: typeString) else {
            return nil
        }

        let date = dateTimestamp.dateValue()

        let transaction = Transaction(
            amount: amount,
            note: note,
            date: date,
            type: type
        )
        // FIX: Cannot set id directly on @Model
        // transaction.id = id

        if let categoryName = data["categoryName"] as? String,
           let categoryIcon = data["categoryIcon"] as? String,
           let categoryColor = data["categoryColor"] as? String {
            let category = Category(
                name: categoryName,
                type: type,
                icon: categoryIcon,
                colorHex: categoryColor
            )
            transaction.category = category
        }

        return transaction
    }

    func savePocket(_ pocket: Pocket) async {
        guard let userID = currentUserID else { return }

        let familyID = await getFamilyID()

        var pocketData: [String: Any] = [
            "id": pocket.id.uuidString,
            "name": pocket.name,
            "pocketType": pocket.pocketType.rawValue,
            "targetAmount": pocket.targetAmount,
            "balance": pocket.balance,
            "allocationPercentage": pocket.allocationPercentage,
            "icon": pocket.icon,
            "colorHex": pocket.colorHex,
            "userID": userID,
            "updatedAt": Timestamp(date: Date())
        ]

        if let familyID = familyID {
            pocketData["familyID"] = familyID
        }

        do {
            try await db.collection("pockets").document(pocket.id.uuidString).setData(pocketData)
            print("✅ Pocket saved: \(pocket.name)")
        } catch {
            print("❌ Error saving pocket: \(error)")
        }
    }

    func fetchPockets() async -> [Pocket] {
        guard let userID = currentUserID else { return [] }

        let familyID = await getFamilyID()

        do {
            var query: Query = db.collection("pockets")

            if let familyID = familyID {
                query = query.whereField("familyID", isEqualTo: familyID)
            } else {
                query = query.whereField("userID", isEqualTo: userID)
            }

            let snapshot = try await query.getDocuments()

            return snapshot.documents.compactMap { parsePocket(from: $0.data()) }

        } catch {
            print("❌ Error fetching pockets: \(error)")
            return []
        }
    }

    private func parsePocket(from data: [String: Any]) -> Pocket? {
        guard let idString = data["id"] as? String,
              let id = UUID(uuidString: idString),
              let name = data["name"] as? String,
              let typeString = data["pocketType"] as? String,
              let type = PocketType(rawValue: typeString),
              let icon = data["icon"] as? String,
              let colorHex = data["colorHex"] as? String else {
            return nil
        }

        let targetAmount = data["targetAmount"] as? Double ?? 0
        let balance = data["balance"] as? Double ?? 0
        let allocationPercentage = data["allocationPercentage"] as? Double ?? 10

        let pocket = Pocket(
            name: name,
            pocketType: type,
            targetAmount: targetAmount,
            balance: balance,
            allocationPercentage: allocationPercentage,
            icon: icon,
            colorHex: colorHex
        )
        // FIX: Cannot set id directly on @Model
        // pocket.id = id
        return pocket
    }

    func listenToTransactions(onUpdate: @escaping ([Transaction]) -> Void) -> ListenerRegistration? {
        guard let userID = currentUserID else { return nil }

        let familyID = Auth.auth().currentUser?.uid

        return db.collection("transactions")
            .order(by: "date", descending: true)
            .limit(to: 50)
            .whereField("familyID", isEqualTo: familyID ?? userID)
            .addSnapshotListener { snapshot, error in
                guard let documents = snapshot?.documents else {
                    print("Error listening: \(error?.localizedDescription ?? "Unknown")")
                    return
                }

                let transactions = documents.compactMap { self.parseTransaction(from: $0.data()) }
                onUpdate(transactions)
            }
    }

    func listenToWallets(onUpdate: @escaping ([Wallet]) -> Void) -> ListenerRegistration? {
        guard let userID = currentUserID else { return nil }

        return db.collection("wallets")
            .whereField("userID", isEqualTo: userID)
            .addSnapshotListener { snapshot, error in
                guard let documents = snapshot?.documents else { return }

                let wallets = documents.compactMap { self.parseWallet(from: $0.data()) }
                onUpdate(wallets)
            }
    }
}
